name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: main

      - run: bundle exec rubocop
        working-directory: main

      - run: bin/test test/automated
        working-directory: main

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clean
        run: git ls-files -z | xargs -0 rm
        working-directory: gh-pages

      - name: Build
        run: bin/site build --output=../gh-pages
        working-directory: main

      - name: Deploy (commit and push)
        working-directory: gh-pages
        run: |
          git add -A
          if ! git diff --cached --quiet ; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -m "Build for $(git rev-parse --short "$GITHUB_SHA")"
            git push
          else
            echo "No changes. Nothing to commit."
          fi
